name: Deployment vlxx69.club

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd desktop/vlxx69_club
            git fetch origin
            git checkout main
            git pull
            docker build -t vlxx69_club .
            docker image prune -f
            docker stop vlxx69_club_container || true
            docker rm vlxx69_club_container || true
            docker run -d --name vlxx69_club_container -p 3333:3000 vlxx69_club
