name: Deployment PhimChillOnline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd desktop/phimchill_online
            git fetch origin
            git checkout main
            git pull
            docker build -t phimchill_online .
            docker image prune -f
            docker stop phimchill_online_container || true
            docker rm phimchill_online_container || true
            docker run -d --name phimchill_online_container -p 5001:3000 phimchill_online
