name: Deployment Phimchillmoi.xyz

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd desktop/phimchillmoi_xyz
            git fetch origin
            git checkout main
            git pull
            docker build -t phimchillmoi_xyz .
            docker image prune -f
            docker stop phimchillmoi_xyz_container || true
            docker rm phimchillmoi_xyz_container || true
            docker run -d --name phimchillmoi_xyz_container -p 5002:3000 phimchillmoi_xyz
